db_username = "sit_postgres"
db_name = "sitpostgresrds"
db_password = "dit_password"
cloudwatch_log_group_name = "sitcloudwatch-log-group"
docker_image_tag = "latest-prod"
lambda_name = "flaskApi-prod"
docker_image_tag = "latest_prod"