lambda_name =  "flaskApi-sit"
db_username = "sit_postgres"
db_password = "sit_password"
cloudwatch_log_group_name = "sitcloudwatch-log-group"
db_name = "sitpostgresrds"
docker_image_tag = "latest-sit"